"use strict";

module.exports = (sequelize, DataTypes) => {
  const Role = sequelize.define(
    "Role",
    {
      import: DataTypes.BOOLEAN,
      content: DataTypes.BOOLEAN,
      anon: DataTypes.BOOLEAN,
      export_local: DataTypes.BOOLEAN,
      export_extern: DataTypes.BOOLEAN,
      query: DataTypes.BOOLEAN,
      auto_query: DataTypes.BOOLEAN,
      delete: DataTypes.BOOLEAN,
      admin: DataTypes.BOOLEAN,
      cd_burner: DataTypes.BOOLEAN,
      create_report: DataTypes.BOOLEAN,
      sharing: DataTypes.BOOLEAN,
      card_sharing: DataTypes.BOOLEAN,
      autorouting: DataTypes.BOOLEAN,
      premium: DataTypes.BOOLEAN,
      create_patient_report: DataTypes.BOOLEAN,
      edit_patient_report: DataTypes.BOOLEAN,
      view_patient_report: DataTypes.BOOLEAN,
      request_patient_report: DataTypes.BOOLEAN,
      delete_report: DataTypes.BOOLEAN,
      addendun: DataTypes.BOOLEAN,
      can_finalize_report: DataTypes.BOOLEAN,
      view_request_report: DataTypes.BOOLEAN,
      delete_req_report: DataTypes.BOOLEAN,
      can_change_report_status: DataTypes.BOOLEAN,
      report_with_pdf: DataTypes.BOOLEAN,
      view_imagin: DataTypes.BOOLEAN,
      delete_imagin: DataTypes.BOOLEAN,
      can_req_imaging: DataTypes.BOOLEAN,
      can_add_radiologist_email: DataTypes.BOOLEAN,
      can_view_assign_caselist: DataTypes.BOOLEAN,
      can_view_admin_caselist: DataTypes.BOOLEAN,
      can_assign_doctors: DataTypes.BOOLEAN,
      can_download_zip: DataTypes.BOOLEAN,
      can_add_table: DataTypes.BOOLEAN,
      share_card_download: DataTypes.BOOLEAN,
      meddream: DataTypes.BOOLEAN,
      view_and_download_light: DataTypes.BOOLEAN,
      view_monitoring: DataTypes.BOOLEAN,
      view_system_monitoring: DataTypes.BOOLEAN,
      view_user_activity: DataTypes.BOOLEAN,
      view_my_dashboard: DataTypes.BOOLEAN,
      signature_compulsory: DataTypes.BOOLEAN,
      moderator: DataTypes.BOOLEAN,
      doctor_description_required: DataTypes.BOOLEAN,
      name: {
        primaryKey: true,
        type: DataTypes.STRING,
      },
      modify: DataTypes.BOOLEAN,
      request_scan: DataTypes.BOOLEAN,
      request_scan_calender: DataTypes.BOOLEAN,
      request_scan_list: DataTypes.BOOLEAN,
      usg_no: DataTypes.BOOLEAN,
      can_delete_request_scan:DataTypes.BOOLEAN,
      view_wsi:DataTypes.BOOLEAN,
      share_card_wsi:DataTypes.BOOLEAN,
      add_manufacture:DataTypes.BOOLEAN,
      add_vendor:DataTypes.BOOLEAN,
      add_store_location:DataTypes.BOOLEAN,
      view_manufacture:DataTypes.BOOLEAN,
      view_vendor:DataTypes.BOOLEAN,
      view_store_location:DataTypes.BOOLEAN,
      change_inventory_min_qty:DataTypes.BOOLEAN,
      change_inventory_qty:DataTypes.BOOLEAN,
      delete_record_excel:DataTypes.BOOLEAN,
      save_inventory:DataTypes.BOOLEAN,
      delete_inventory:DataTypes.BOOLEAN,
      use_inventory:DataTypes.BOOLEAN,
      view_inventory:DataTypes.BOOLEAN,
      view_maintance:DataTypes.BOOLEAN,
      edit_inventory:DataTypes.BOOLEAN,
      can_assign_report_by_role:DataTypes.BOOLEAN,
      can_view_uploader:DataTypes.BOOLEAN,
      can_create_uploader:DataTypes.BOOLEAN,
      can_search_ref_physician:DataTypes.BOOLEAN,
      can_add_logo:DataTypes.BOOLEAN,
      can_search_institution:DataTypes.BOOLEAN,
      can_register_patient:DataTypes.BOOLEAN,
      can_view_appointment:DataTypes.BOOLEAN,
      can_view_demographic:DataTypes.BOOLEAN,
      see_report_label:DataTypes.BOOLEAN,
      edit_report_label:DataTypes.BOOLEAN,
      see_report_type:DataTypes.BOOLEAN,
      edit_report_type:DataTypes.BOOLEAN,
      limit:DataTypes.INTEGER,
      view_registered_user:DataTypes.BOOLEAN,
      
      main_table_checkbox:DataTypes.BOOLEAN,
      main_table_status:DataTypes.BOOLEAN,
      main_table_detail:DataTypes.BOOLEAN,
      main_table_date:DataTypes.BOOLEAN,
      main_table_time:DataTypes.BOOLEAN,
      main_table_patient_name:DataTypes.BOOLEAN,
      main_table_patient_id:DataTypes.BOOLEAN,
      main_table_accession:DataTypes.BOOLEAN,
      main_table_description:DataTypes.BOOLEAN,
      main_table_gender:DataTypes.BOOLEAN,
      main_table_dob:DataTypes.BOOLEAN,
      main_table_age:DataTypes.BOOLEAN,
      main_table_selectBtn:DataTypes.BOOLEAN,
      main_table_viewBtn:DataTypes.BOOLEAN,
      main_table_reportBtn:DataTypes.BOOLEAN,
      can_request_feature:DataTypes.BOOLEAN,
      can_view_request_feature:DataTypes.BOOLEAN,
      main_table_patient_select:DataTypes.BOOLEAN,
      delete_request_feature:DataTypes.BOOLEAN,
      can_transfer:DataTypes.BOOLEAN,
      generate_series:DataTypes.BOOLEAN,
      create_dataset:DataTypes.BOOLEAN,
      dataset_request:DataTypes.BOOLEAN,
      download_dataset_excel:DataTypes.BOOLEAN,
      view_dataset:DataTypes.BOOLEAN,
      view_my_dataset:DataTypes.BOOLEAN,
      copy_osimis:DataTypes.BOOLEAN,
      copy_stone:DataTypes.BOOLEAN,
      copy_download_zip:DataTypes.BOOLEAN,
      main_table_modality_view:DataTypes.BOOLEAN,
      delete_dataset:DataTypes.BOOLEAN,
      manage_report_template:DataTypes.BOOLEAN,
      send_report_dicom:DataTypes.BOOLEAN,
      manage_auto_send_ai:DataTypes.BOOLEAN,
      patient_management:DataTypes.BOOLEAN,
      view_radiant:DataTypes.BOOLEAN,
      view_horos:DataTypes.BOOLEAN,
      view_weasis:DataTypes.BOOLEAN,
      preload_osimis:DataTypes.BOOLEAN,
      view_osimis:DataTypes.BOOLEAN,
      view_aiViewer:DataTypes.BOOLEAN,
      view_ohif:DataTypes.BOOLEAN,
      download_report:DataTypes.BOOLEAN,
      print_report:DataTypes.BOOLEAN,
      view_padiLabel:DataTypes.BOOLEAN
    },
    {}
  );
  Role.associate = function (models) {
    Role.hasOne(models.User, {
      foreignKey: "role",
      as: "role",
    }),
      Role.hasOne(models.DistantUser, {
        foreignKey: "local_role",
        as: "local_role",
      }),
      Role.hasOne(models.RegisteredPatient,{
        foreignKey: "role",
        as: "RegisteredPatient_role",
      });
  };
  return Role;
};
