import CHEST_X_RAY from './Chest-Xray';
import MAMMOGRAM from './MAMMOGRAM';
import CERVICAL from './CERVICAL';
import ABDOMINAL from './ABDOMINAL-RADIOGRAPH';
import KUB_XRAY from './KUB-RADIOGRAPH';
import SPINE_XRAY from './SPINE-XRAY';
import KNEE_XRAY from './KNEE-XRAY';
import CHEST_RADIOGRAPH from './CHEST-RADIOGRAPH';
import LIMB_XRAY from './LIMB-XRAY';
import CT_UROGRAPHY from './CTUROGRAPHY';
import CT_ABDOMEN from './CTABDOMEN';
import CTPA_PULMONARY from './CTPA-PULMONARY';
import PARANASAL_SINUS from './PARANASAL_SINUS';
import PLAIN_CT_BRAIN from './PLAIN_CT_BRAIN';
import CECT_RENAL from './CECT_RENAL';
import HRCT_THORAX from './HRCT_THORAX';
import US_ABDOMEN_PELVIS_MALE from './US_ABDOMEN_PELVIS_MALE';
import US_ABDOMEN_PELVIS_FEMALE from './US_ABDOMEN_PELVIS_FEMALE';

// tukar template
export { CHEST_X_RAY, MAMMOGRAM, CERVICAL, ABDOMINAL, KUB_XRAY, SPINE_XRAY, KNEE_XRAY, CHEST_RADIOGRAPH, LIMB_XRAY
    , CT_UROGRAPHY, CT_ABDOMEN, CTPA_PULMONARY, PARANASAL_SINUS, PLAIN_CT_BRAIN, CECT_RENAL, HRCT_THORAX
, US_ABDOMEN_PELVIS_MALE, US_ABDOMEN_PELVIS_FEMALE }
