const Role = require("../repository/Role");
const {
  OTJSConflictException,
  OTJSBadRequestException,
} = require("./../Exceptions/OTJSErrors");

class Roles {
  static async createRoles(payload) {
    const roles = await Role.getRole(payload.name);

    if (roles) {
      throw new OTJSConflictException("This roles already exist");
    }

    return Role.create(
      payload.name,
      payload.import,
      payload.content,
      payload.anon,
      payload.exportLocal,
      payload.exportExtern,
      payload.query,
      payload.autoQuery,
      payload.delete,
      payload.modify,
      payload.cd_burner,
      payload.create_report,
      payload.sharing,
      payload.card_sharing,
      payload.autorouting,
      payload.admin,
      payload.premium,
      payload.create_patient_report,
      payload.edit_patient_report,
      payload.view_patient_report,
      payload.request_patient_report,
      payload.delete_report,
      payload.addendun,
      payload.can_finalize_report,
      payload.view_request_report,
      payload.delete_req_report,
      payload.can_change_report_status,
      payload.report_with_pdf,
      payload.view_imagin,
      payload.delete_imagin,
      payload.can_req_imaging,
      payload.can_add_radiologist_email,
      payload.can_view_assign_caselist,
      payload.can_view_admin_caselist,
      payload.can_assign_doctors,
      payload.can_download_zip,
      payload.can_add_table,
      payload.share_card_download,
      payload.meddream,
      payload.view_and_download_light,
      payload.view_monitoring,
      payload.view_system_monitoring,
      payload.view_user_activity,
      payload.view_my_dashboard,
      payload.signature_compulsory,
      payload.moderator,
      payload.doctor_description_required,
      payload.request_scan,
      payload.request_scan_calender,
      payload.request_scan_list,
      payload.usg_no,
      payload.can_delete_request_scan,
      payload.view_wsi,
      payload.share_card_wsi,
      payload.add_manufacture,
      payload.add_vendor,
      payload.add_store_location,
      payload.view_manufacture,
      payload.view_vendor,
      payload.view_store_location,
      payload.change_inventory_min_qty,
      payload.change_inventory_qty,
      payload.delete_record_excel,
      payload.save_inventory,
      payload.delete_inventory,
      payload.use_inventory,
      payload.view_inventory,
      payload.view_maintance,
      payload.edit_inventory,
      payload.can_assign_report_by_role,
      payload.can_view_uploader,
      payload.can_create_uploader,
      payload.can_search_ref_physician,
      payload.can_add_logo,
      payload.can_search_institution,
      payload.can_register_patient,
      payload.can_view_appointment,
      payload.can_view_demographic,
      payload.see_report_label,
      payload.edit_report_label,
      payload.see_report_type,
      payload.edit_report_type,
      payload.limit,
      payload.view_registered_user,

      payload.main_table_checkbox,
      payload.main_table_status,
      payload.main_table_detail,
      payload.main_table_date,
      payload.main_table_time,
      payload.main_table_patient_name,
      payload.main_table_patient_id,
      payload.main_table_accession,
      payload.main_table_description,
      payload.main_table_gender,
      payload.main_table_dob,
      payload.main_table_age,
      payload.main_table_selectBtn,
      payload.main_table_viewBtn,
      payload.main_table_reportBtn,

      payload.can_request_feature,
      payload.can_view_request_feature,
      payload.main_table_patient_select,
      payload.delete_request_feature,
      payload.can_transfer,
      payload.generate_series,

      payload.create_dataset,
      payload.dataset_request,

      payload.download_dataset_excel,
      payload.view_dataset,
      payload.view_my_dataset,
      payload.copy_osimis,
      payload.copy_stone,
      payload.copy_download_zip,

      payload.main_table_modality_view,
      payload.delete_dataset,
      payload.manage_report_template,
      payload.send_report_dicom,
      payload.manage_auto_send_ai,
      payload.patient_management,
      payload.view_radiant,
      payload.view_horos,
      payload.view_osimis,
      payload.view_aiViewer,
      payload.download_report,
      payload.print_report,
      payload.view_padiLabel
    );
  }

  static async getRole(name){
    return await Role.getRole(name);
  }
  static async getAllRoles() {
    return Role.getAllRole();
  }

  static async getAllRolesName(){
    return Role.getAllRoleName();
  }
  static getPermission(name) {
    return Role.getRoleByName(name);
  }

  static deleteRole(name) {
    if (name === "admin")
      throw new OTJSBadRequestException("Can't delete Admin Role");
    return Role.delete(name);
  }

  static modifyRoles(name, payload) {
    //uncomment below code after enabling premium sharing with admin
    // if (name === 'admin') {
    //   throw new OTSBadRequestException('Can\'t modify Admin Role')
    // };
    return Role.update(
      name,
      payload.import,
      payload.content,
      payload.anon,
      payload.exportLocal,
      payload.exportExtern,
      payload.query,
      payload.autoQuery,
      payload.delete,
      payload.modify,
      payload.cd_burner,
      payload.create_report,
      payload.sharing,
      payload.card_sharing,
      payload.autorouting,
      payload.admin,
      payload.premium,
      payload.create_patient_report,
      payload.edit_patient_report,
      payload.view_patient_report,
      payload.request_patient_report,
      payload.delete_report,
      payload.addendun,
      payload.can_finalize_report,
      payload.view_request_report,
      payload.delete_req_report,
      payload.can_change_report_status,
      payload.report_with_pdf,
      payload.view_imagin,
      payload.delete_imagin,
      payload.can_req_imaging,
      payload.can_add_radiologist_email,
      payload.can_view_assign_caselist,
      payload.can_view_admin_caselist,
      payload.can_assign_doctors,
      payload.can_download_zip,
      payload.can_add_table,
      payload.share_card_download,
      payload.meddream,
      payload.view_and_download_light,
      payload.view_monitoring,
      payload.view_system_monitoring,
      payload.view_user_activity,
      payload.view_my_dashboard,
      payload.signature_compulsory,
      payload.moderator,
      payload.doctor_description_required,
      payload.request_scan,
      payload.request_scan_calender,
      payload.request_scan_list,
      payload.usg_no,
      payload.can_delete_request_scan,
      payload.view_wsi,
      payload.share_card_wsi,
      payload.add_manufacture,
      payload.add_vendor,
      payload.add_store_location,
      payload.view_manufacture,
      payload.view_vendor,
      payload.view_store_location,
      payload.change_inventory_min_qty,
      payload.change_inventory_qty,
      payload.delete_record_excel,
      payload.save_inventory,
      payload.delete_inventory,
      payload.use_inventory,
      payload.view_inventory,
      payload.view_maintance,
      payload.edit_inventory,
      payload.can_assign_report_by_role,
      payload.can_view_uploader,
      payload.can_create_uploader,
      payload.can_search_ref_physician,
      payload.can_add_logo,
      payload.can_search_institution,
      payload.can_register_patient,
      payload.can_view_appointment,
      payload.can_view_demographic,
      payload.see_report_label,
      payload.edit_report_label,
      payload.see_report_type,
      payload.edit_report_type,
      payload.limit,
      payload.view_registered_user,

      payload.main_table_checkbox,
      payload.main_table_status,
      payload.main_table_detail,
      payload.main_table_date,
      payload.main_table_time,
      payload.main_table_patient_name,
      payload.main_table_patient_id,
      payload.main_table_accession,
      payload.main_table_description,
      payload.main_table_gender,
      payload.main_table_dob,
      payload.main_table_age,
      payload.main_table_selectBtn,
      payload.main_table_viewBtn,
      payload.main_table_reportBtn,

      payload.can_request_feature,
      payload.can_view_request_feature,
      payload.main_table_patient_select,
      payload.delete_request_feature,
      payload.can_transfer,
      payload.generate_series,

      payload.create_dataset,
      payload.dataset_request,
      
      payload.download_dataset_excel,
      payload.view_dataset,
      payload.view_my_dataset,
      payload.copy_osimis,
      payload.copy_stone,
      payload.copy_download_zip,

      payload.main_table_modality_view,
      payload.delete_dataset,
      
      payload.manage_report_template,
      payload.send_report_dicom,
      payload.manage_auto_send_ai,
      payload.patient_management,
      payload.view_radiant,
      payload.view_horos,
      payload.view_osimis,
      payload.view_aiViewer,
      payload.download_report,
      payload.print_report,
      payload.view_padiLabel
    );
  }
}

module.exports = Roles;
